"use client";

import "./globals.css";
import localFont from "next/font/local";
import { createTheme, ThemeProvider } from "@mui/material/styles";
import TextField from "@mui/material/TextField";
import rtlPlugin from "stylis-plugin-rtl";
import { prefixer } from "stylis";
import { CacheProvider } from "@emotion/react";
import createCache from "@emotion/cache";

const theme = createTheme({
  direction: "rtl",
  palette: {
    // mode: outerTheme.palette.mode,
  },
  typography: {
    fontFamily: `'__shabnamFont_fa1468', '__shabnamFont_Fallback_fa1468'`,
  },
});

const cacheRtl = createCache({
  key: "muirtl",
  stylisPlugins: [prefixer, rtlPlugin],
});

const shabnamFont = localFont({
  src: "./../public/font/shabnam/Shabnam-Light-FD.ttf",
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <body className={shabnamFont.className}>
        <CacheProvider value={cacheRtl}>
          <ThemeProvider theme={theme}>{children}</ThemeProvider>
        </CacheProvider>
      </body>
    </html>
  );
}
