import "./globals.css";
import localFont from "next/font/local";

const shabnamFont = localFont({
  src: "./../public/font/shabnam/Shabnam-Light-FD.ttf",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <body className={shabnamFont.className}>{children}</body>
    </html>
  );
}
